services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: GeoTaggingApp
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
      - app_writable:/var/www/html/writable
      - app_uploads:/var/www/html/public/uploads
    ports:
      - "9009:80"
    env_file:
      - .env
    # networks:
    #   - appnet
volumes:
  app_writable:
  app_uploads:
networks:
  mysql-net:
    external: true
